# QUIET_SUBDIR0 = +$(MAKE) -C
# QUIET_SUBDIR0 = +@subdir=

# QUIET_SUBDIR1 = ;$(NO_SUBDIR) echo '	' SUBDIR $$subdir; \
# 		$(MAKE) $(PRINT_DIR) -C $$subdir

# NO_SUBDIR = :
# PRINT_DIR = --no-print-directory

# make -C +@subdir=git;
# echo '	' SUBDIR git;
# make --no-print-directory -C git -f ../cgit.mk ../cgit NO_CURL=1

all: hello_world
	echo "hello world"
